config/routes.rb
Icol::Engine.routes.draw do
  resources :notifications, only: [:index, :show] do
    collection do
      get :index
      put :index
    end
    member do
      get :audit_steps
    end
  end

  resources :notify_transactions
  
  resources :customers do
    collection do
      get :index
      put :index
    end
    member do
      get :audit_logs
      put :approve
    end
  end
  
  resources :validate_steps, only: [:index, :show] do
    collection do
      get :index
      put :index
    end
  end
end

app/models/icol/app.rb
module Icol
  class App < ActiveRecord::Base
  end
end

app/models/icol/customer.rb
module Icol
  class Customer < ActiveRecord::Base
    include Approval2::ModelAdditions
    
    belongs_to :created_user, class_name: 'User', foreign_key: 'created_by'
    belongs_to :updated_user, class_name: 'User', foreign_key: 'updated_by'
    
    SETTING_TYPES = ['text','number','date']
    validate :atleast_one_url_should_present?
    
    validates_presence_of :customer_code, :app_code, :is_enabled
    validates_numericality_of :retry_notify_in_mins, :max_retries_for_notify, allow_blank: true
    validates_uniqueness_of :customer_code, scope: [:approval_status]
    validates_length_of :http_username, maximum: 100, allow_blank: true
    validates_length_of :http_password, maximum: 100, allow_blank: true
    
    validates :customer_code, format: {with: /\A[a-z|A-Z|0-9|\.|\-]+\z/, :message => 'Invalid format, expected format is : {[a-z|A-Z|0-9|\.|\-]}' }, length: { maximum: 15 }
    validates :app_code, format: {with: /\A[a-z|A-Z|0-9|\.|\-]+\z/, :message => 'Invalid format, expected format is : {[a-z|A-Z|0-9|\.|\-]}' }, length: { maximum: 50 }
    validates :notify_url, :validate_url, format: {with: URI.regexp, :message => 'Invalid format, expected format is : https://example.com' }, length: { maximum: 100 }, allow_blank: true
      
    store :setting1, accessors: [:setting1_name, :setting1_type, :setting1_value], coder: JSON
    store :setting2, accessors: [:setting2_name, :setting2_type, :setting2_value], coder: JSON
    store :setting3, accessors: [:setting3_name, :setting3_type, :setting3_value], coder: JSON
    store :setting4, accessors: [:setting4_name, :setting4_type, :setting4_value], coder: JSON
    store :setting5, accessors: [:setting5_name, :setting5_type, :setting5_value], coder: JSON
    
    validate :settings_should_be_correct
    validate :password_should_be_present
    
    validates_presence_of :setting1_name, if: "setting1_name.blank? && !setting2_name.blank?", message: "can't be blank when Setting2 name is present"
    validates_presence_of :setting2_name, if: "setting2_name.blank? && !setting3_name.blank?", message: "can't be blank when Setting3 name is present"
    validates_presence_of :setting3_name, if: "setting3_name.blank? && !setting4_name.blank?", message: "can't be blank when Setting4 name is present"
    validates_presence_of :setting4_name, if: "setting4_name.blank? && !setting5_name.blank?", message: "can't be blank when Setting5 name is present"
  
    before_save :set_settings_cnt
    before_save :encrypt_password
    after_save :decrypt_password
    after_find :decrypt_password
  
    private
  
    def atleast_one_url_should_present?
      if notify_url.blank? & validate_url.blank?
        errors.add :base, "Require atleast one of them notify url, validate url"
      end
    end
    
    def set_settings_cnt
      self.settings_cnt = 0
      self.settings_cnt += 1 unless setting1_name.blank?
      self.settings_cnt += 1 unless setting2_name.blank?
      self.settings_cnt += 1 unless setting3_name.blank?
      self.settings_cnt += 1 unless setting4_name.blank?
      self.settings_cnt += 1 unless setting5_name.blank?
    end
  
    def settings_should_be_correct
      validate_setting(:setting1_value, setting1_name, setting1_type, setting1_value)
      validate_setting(:setting2_value, setting2_name, setting2_type, setting2_value)
      validate_setting(:setting3_value, setting3_name, setting3_type, setting3_value)
      validate_setting(:setting4_value, setting4_name, setting4_type, setting4_value)
      validate_setting(:setting5_value, setting5_name, setting5_type, setting5_value)
    end
  
    def validate_setting(attr_name, setting_name, setting_type, setting_value)
      errors.add(attr_name, "can't be blank") if setting_name.present? && setting_value.blank?
      if setting_name.present? and setting_value.present?
        errors.add(attr_name, "invalid format, the correct format is yyyy-mm-dd") if (setting_type == "date" && setting_value =~ /\A\d{4}\-\d{2}\-\d{2}+$\z/).nil?
        Time.zone.parse setting_value rescue errors.add(attr_name, "is not a date") if setting_type == "date"
        errors.add(attr_name, "is longer than maximum (100)") if setting_type == "text" && setting_value.length > 100
        errors.add(attr_name, "should include only digits") if setting_type == "number" && (setting_value =~ /\A[0-9]+$\z/).nil?
      end
    end
  
    def decrypt_password
      self.http_password = DecPassGenerator.new(http_password,ENV['CONSUMER_KEY'], ENV['CONSUMER_SECRET']).generate_decrypted_data if http_password.present?
    end
    
    def encrypt_password
      self.http_password = EncPassGenerator.new(self.http_password, ENV['CONSUMER_KEY'], ENV['CONSUMER_SECRET']).generate_encrypted_password unless http_password.to_s.empty?
    end
    
    def password_should_be_present
      errors[:base] << "HTTP Password can't be blank if HTTP Username is present" if self.http_username.present? and (self.http_password.blank? or self.http_password.nil?)
    end
  end
end

app/models/icol/invxp.rb
class Invxp < ActiveRecord::Base
  self.abstract_class = true
  establish_connection "invxp_#{Rails.env}"
end

app/models/icol/notification.rb
module Icol
  class Notification < ActiveRecord::Base
    has_many :notify_steps
  end
end

app/models/icol/notify_step.rb
module Icol
  class NotifyStep < ActiveRecord::Base
    lazy_load :req_header, :rep_header, :req_bitstream, :rep_bitstream, :fault_bitstream
    belongs_to :notification, foreign_key: :icol_notification_id
  end
end

app/models/icol/notify_transaction.rb
module Icol
  class NotifyTransaction < Invxp
    self.primary_key = :trnsctn_nmbr
    self.table_name = "trnsctn_stt"
    before_validation :set_created_at
    
    validates_presence_of :template_id, :compny_id, :comapny_name, :trnsctn_mode, :trnsctn_nmbr, :payment_status, :template_data
    validates_uniqueness_of :trnsctn_nmbr
    validates :payment_status, length: { maximum: 3 }
    validates :trnsctn_mode, length: { maximum: 3 }
    validates :template_data, length: { maximum: 1000 }
    validates :comapny_name, length: { maximum: 100 }
    validates_numericality_of :template_id, :compny_id, :trnsctn_nmbr
    
    def set_created_at
      self.crtd_date_time = Time.now
    end
  end
end

app/models/icol/validate_step.rb
module Icol
  class ValidateStep < ActiveRecord::Base
    lazy_load :up_req_header, :up_rep_header, :up_req_bitstream, :up_rep_bitstream, :req_bitstream, :rep_bitstream, :fault_bitstream
  end
end

app/controllers/icol/application_controller.rb
module Icol
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/icol/customers_controller.rb
module Icol
  class CustomersController < ApplicationController
    authorize_resource
    before_filter :authenticate_user!
    before_filter :block_inactive_user!
    respond_to :json
    include Approval2::ControllerAdditions
    include ApplicationHelper
  
    def new
      @customer = Customer.new
    end
  
    def create
      @customer = Customer.new(customer_params)
      if !@customer.valid?
        render "new"
      else
        @customer.created_by = current_user.id
        @customer.save!
        flash[:alert] = 'Customer successfully created and is pending for approval'
        redirect_to @customer
      end
    end
  
    def update
      @customer = Customer.unscoped.find_by_id(params[:id])
      @customer.attributes = customer_params
      if !@customer.valid?
        render "edit"
      else
        @customer.updated_by = current_user.id
        @customer.save!
        flash[:alert] = 'Customer successfully modified successfully'
        redirect_to @customer
      end
      rescue ActiveRecord::StaleObjectError
        @customer.reload
        flash[:alert] = 'Someone edited the customer the same time you did. Please re-apply your changes to the customer.'
        render "edit"
    end 
  
    def show
      @customer = Customer.unscoped.find_by_id(params[:id])
    end
  
    def index
      if request.get?
        @searcher = CustomerSearcher.new(params.permit(:page, :approval_status))
      else
        @searcher = CustomerSearcher.new(search_params)
      end
      @records = @searcher.paginate
    end
  
    def audit_logs
      @record = Customer.unscoped.find(params[:id]) rescue nil
      @audit = @record.audits[params[:version_id].to_i] rescue nil
    end
  
    def approve
      redirect_to main_app.unapproved_records_path(group_name: 'icol')
    end
  
    private
  
    def customer_params
      params.require(:customer).permit(:customer_code, :app_code, :settings_cnt, 
      :lock_version, :last_action, :updated_by, :notify_url, :validate_url, 
      :http_username, :http_password, :approval_status, :approved_version, 
      :approved_id, :max_retries_for_notify, :retry_notify_in_mins,
      :setting1_name, :setting1_type, :setting1_value, 
      :setting2_name, :setting2_type, :setting2_value, 
      :setting3_name, :setting3_type, :setting3_value, 
      :setting4_name, :setting4_type, :setting4_value,
      :setting5_name, :setting5_type, :setting5_value
      )
    end
    
    def search_params
      params.permit(:page, :approval_status, :app_code, :customer_code)
    end
    
  end
end

app/controllers/icol/notifications_controller.rb
module Icol
  class NotificationsController < ApplicationController
    authorize_resource
    before_filter :authenticate_user!
    before_filter :block_inactive_user!
    respond_to :json
    include ApplicationHelper
    
    def index
      if request.get?
        @searcher = NotificationSearcher.new(params.permit(:page))
      else
        @searcher = NotificationSearcher.new(search_params)
      end
      @records = @searcher.paginate
    end
    
    def show
      @icol_notification = Notification.find(params[:id])
    end
    
    def audit_steps
      icol_notification = Notification.find(params[:id])
      steps = icol_notification.icol_notify_steps
      @steps = steps.order("id desc").paginate(page: params[:page], per_page: 10)
    end
    
    private
    
    def search_params
      params.permit(:page, :app_code, :customer_code, :txn_number, :status_code, :payment_status)
    end
  
  end
end

app/controllers/icol/notify_transactions_controller.rb
module Icol
  class NotifyTransactionsController < ApplicationController
    authorize_resource
    before_filter :authenticate_user!
    before_filter :block_inactive_user!
    respond_to :json
    include ApplicationHelper
    
    def new
      @notify_transaction = NotifyTransaction.new
    end
  
    def create
      @notify_transaction = NotifyTransaction.new(params[:notify_transaction])
      if !@notify_transaction.valid?
        render "new"
      else
        @notify_transaction.save!
        flash[:alert] = 'Notify Transaction successfully created'
        redirect_to notify_transactions_path
      end
    end
  
    def edit
      @notify_transaction = NotifyTransaction.find(params[:id])
    end
  
    def update
      @notify_transaction = NotifyTransaction.find(params[:id])
      @notify_transaction.attributes = notify_transaction_params
      if !@notify_transaction.valid?
        render "edit"
      else
        @notify_transaction.save!
        flash[:alert] = 'Notify Transaction successfully modified'
        redirect_to notify_transactions_path
      end
    end
  
    def index
      icol_notify_transactions = NotifyTransaction.order("crtd_date_time desc")
      @icol_notify_transactions_count = icol_notify_transactions.count
      @icol_notify_transactions = icol_notify_transactions.paginate(:per_page => 10, :page => params[:page]) rescue []
    end
  
    def show
      @notify_transaction = NotifyTransaction.find(params[:id])
    end
  
    def destroy
      notify_transaction = NotifyTransaction.find(params[:id])
      if notify_transaction.destroy
        flash[:alert] = "Notify Transaction record has been deleted!"
      else
        flash[:alert] = "Notify Transaction record cannot be deleted!"
      end
      redirect_to notify_transactions_path
    end
  
    private
      def notify_transaction_params
        params.require(:notify_transaction).permit(:template_id, :compny_id, :comapny_name, :trnsctn_mode, :trnsctn_nmbr, :payment_status,:template_data)
      end
  end
end

app/controllers/icol/validate_steps_controller.rb
module Icol
  class ValidateStepsController < ApplicationController
    authorize_resource
    before_filter :authenticate_user!
    before_filter :block_inactive_user!
    respond_to :json
    include ApplicationHelper
    
    def index
      if request.get?
        @searcher = ValidateStepSearcher.new(params.permit(:page))
      else
        @searcher = ValidateStepSearcher.new(search_params)
      end
      @records = @searcher.paginate
    end
    
    def show
      @validate_step = ValidateStep.find_by_id(params[:id])
    end
    
    private
  
    def search_params
      params.permit(:page, :app_code, :customer_code, :step_name, :status_code, :from_request_timestamp, :to_request_timestamp, :from_reply_timestamp, :to_reply_timestamp)
    end
  end
end

app/helpers/icol/application_helper.rb
module Icol
  module ApplicationHelper
  end
end

app/views/icol/notify_transactions/_form.html.haml
= simple_form_for @notify_transaction, :html => {:class=>'form-horizontal', :autocomplete=>"off", :id => "icol_notify_transaction_form"} do |f|
  .control-group
    = f.label ' '
    #msg-error
      = error_message_for(@notify_transaction, :base, :prepend_text => "")

  .form-main{:style=>"width: 100%;"}
    .control-group
      = f.label :compny_id, "*Company Id", :class => 'control-label'
      = f.text_field :compny_id
      #msg-error
        = error_message_for(@notify_transaction, :compny_id, :prepend_text => "")
    .control-group
      = f.label :comapny_name, "*Company Name", :class => 'control-label'
      = f.text_field :comapny_name, :maxlength => 100
      #msg-error
        = error_message_for(@notify_transaction, :comapny_name, :prepend_text => "")
    .control-group
      = f.label :template_id, "*Template Id", :class => 'control-label'
      = f.text_field :template_id
      #msg-error
        = error_message_for(@notify_transaction, :template_id, :prepend_text => "")
    .control-group
      = f.label :template_data, "*Template Data", :class => 'control-label'
      = f.text_area :template_data, :maxlength => 1000
      #msg-error
        = error_message_for(@notify_transaction, :template_data, :prepend_text => "")
    .control-group
      = f.label :trnsctn_mode, "*Transaction Mode", :class => 'control-label'
      = f.text_field :trnsctn_mode, :maxlength => 3
      #msg-error
        = error_message_for(@notify_transaction, :trnsctn_mode, :prepend_text => "")
    .control-group
      = f.label :trnsctn_nmbr, "*Transaction Number", :class => 'control-label'
      = f.text_field :trnsctn_nmbr
      #msg-error
        = error_message_for(@notify_transaction, :trnsctn_nmbr, :prepend_text => "")
    .control-group
      = f.label :payment_status, "*Payment Status", :class => 'control-label'
      = f.text_field :payment_status, :maxlength => 3
      #msg-error
        = error_message_for(@notify_transaction, :payment_status, :prepend_text => "")
  .form-actions
    - (f.object.new_record?) ? label_name = "Create" : label_name = "Update"
    = f.button "submit" ,:class=>"btn btn-primary", :id => 'submit_notify_transaction', :value => label_name + ' Notify Transaction'
    = link_to :Cancel, notify_transactions_path, :name => 'cancel', :class=>"cancel btn"

app/views/icol/notify_transactions/edit.html.haml
%h1 Edit I-Collect Notify Transaction

= render 'form'

app/views/icol/notify_transactions/index.html.haml
%br
= link_to 'New I-Collect Notify Transaction', new_notify_transaction_path
%br
%br
%h1 Listing of I-Collect Notify Transactions
%br
= "Total Count: #{@icol_notify_transactions_count}"
%br
= will_paginate @icol_notify_transactions
%br

%table.table.table-bordered.table-striped.table-hover
  %thead
    %tr
      %th{:style=>'text-align:left; background-color: lightblue;'}
      %th{:style=>'text-align:left; background-color: lightblue;'}
      %th{:style=>'text-align:left; background-color: lightblue;'}
      %th{:style=>'text-align:left; background-color: lightblue;'} 
        Company Name
      %th{:style=>'text-align:left; background-color: lightblue;'} 
        Transaction Mode
      %th{:style=>'text-align:left; background-color: lightblue;'} 
        Transaction Number
      %th{:style=>'text-align:left; background-color: lightblue;'} 
        Payment Status

  %tbody
    - @icol_notify_transactions.each do |notify_transaction|
      %tr
        %td{:style=>'text-align:left;'}
          = link_to 'Show', notify_transaction
        %td{:style=>'text-align:left;'}
          = link_to 'Edit', edit_notify_transaction_path(notify_transaction)
        %td{:style=>'text-align:left;'}
          = link_to 'Delete', notify_transaction, :method => :delete, :data => { :confirm => 'Are you sure?' }
        %td{:style=>'text-align:left;'}
          = notify_transaction.comapny_name
        %td{:style=>'text-align:left;'}
          = notify_transaction.trnsctn_mode
        %td{:style=>'text-align:left;'}
          = notify_transaction.trnsctn_nmbr
        %td{:style=>'text-align:left;'}
          = notify_transaction.payment_status

app/views/icol/notify_transactions/new.html.haml
%h1 New I-Collect Notify Transactions

= render 'form'

app/views/icol/notify_transactions/show.html.haml
.form-horizontal.show_form
  .form-main-with-color{:style=>'background-color: #F1F2F8; height: 662px;'}
    #form-details
      %h3 I-Collect Notify Transaction 
      %br
      %p{:style => 'text-align:left; padding-left:6px; padding-bottom:17px'}
        - can = can? :edit, @notify_transaction
        %a.btn{:href => "#{!(can) ? '#' : '/icol_notify_transactions/' + @notify_transaction.id.to_s + '/edit'}", :role => "button", :class => "btn btn-primary #{(can) ? '' : 'disabled'}"} Edit

      %table.table.no-border{:style=>"table-layout: fixed; width: 100%;"}
        - if !@notify_transaction.nil?
          %tr
            %td.label Company Id
            %td.value
              = @notify_transaction.compny_id
            %td
          %tr
            %td.label Company Name
            %td.value
              = @notify_transaction.comapny_name
            %td
          %tr
            %td.label Transaction Mode
            %td.value
              = @notify_transaction.trnsctn_mode
            %td
          %tr
            %td.label Transaction Number
            %td.value
              = @notify_transaction.trnsctn_nmbr
            %td
          %tr
            %td.label Payment Status
            %td.value
              = @notify_transaction.payment_status
            %td
          %tr
            %td.label Template ID
            %td.value
              = @notify_transaction.template_id
            %td          
          %tr
            %td.label Template Data
            %td.value
              = @notify_transaction.template_data
            %td
          %tr
            %td.label Template Data
            %td.value
              = @notify_transaction.template_data
            %td
          %tr
            %td.label Created At
            %td.value
              = @notify_transaction.crtd_date_time.try(:strftime, "%d/%m/%Y %I:%M%p")
            %td
      = link_to 'Back to Notify Transcations', notify_transactions_path